#!/bin/sh
# ClawICU - OpenClaw Emergency Rescue Script
# Version: 0.1.0
# Usage: curl -fsSL https://xagent.icu/rescue.sh | sh
# Or: curl -fsSL https://xagent.icu/api/v1/rescue-script | sh
#
# This script detects, diagnoses, and repairs common OpenClaw issues:
# - Config file corruption
# - Plugin failures  
# - Gateway crashes
# - Port conflicts
# - Daemon not running
# - Credential problems

set -e

VERSION="0.1.0"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# Detect OS
detect_os() {
    if [ "$(uname)" = "Darwin" ]; then
        OS="macos"
    elif [ -f /etc/os-release ]; then
        . /etc/os-release
        OS="$ID"
    elif [ -f /etc/alpine-release ]; then
        OS="alpine"
    else
        OS="linux"
    fi
}

# Print colored output
print_header() {
    printf "${BOLD}${CYAN}=== ClawICU v${VERSION} - OpenClaw Emergency Rescue ===${RESET}\n\n"
}

print_status() {
    printf "${BLUE}[INFO]${RESET} %s\n" "$1"
}

print_success() {
    printf "${GREEN}[OK]${RESET} %s\n" "$1"
}

print_warning() {
    printf "${YELLOW}[WARN]${RESET} %s\n" "$1"
}

print_error() {
    printf "${RED}[ERROR]${RESET} %s\n" "$1"
}

print_diagnose() {
    printf "${CYAN}[DIAG]${RESET} %s\n" "$1"
}

# Check if OpenClaw is installed
check_openclaw() {
    print_status "Checking OpenClaw installation..."
    
    if command -v openclaw >/dev/null 2>&1; then
        OPENCLAW_PATH=$(command -v openclaw)
        print_success "OpenClaw found at: $OPENCLAW_PATH"
        return 0
    fi
    
    # Common installation paths
    if [ -f "/usr/local/bin/openclaw" ]; then
        OPENCLAW_PATH="/usr/local/bin/openclaw"
        print_success "OpenClaw found at: $OPENCLAW_PATH"
        return 0
    elif [ -f "/usr/bin/openclaw" ]; then
        OPENCLAW_PATH="/usr/bin/openclaw"
        print_success "OpenClaw found at: $OPENCLAW_PATH"
        return 0
    elif [ -f "$HOME/.openclaw/bin/openclaw" ]; then
        OPENCLAW_PATH="$HOME/.openclaw/bin/openclaw"
        print_success "OpenClaw found at: $OPENCLAW_PATH"
        return 0
    fi
    
    print_warning "OpenClaw not found in PATH"
    return 1
}

# Get OpenClaw version
get_version() {
    if command -v openclaw >/dev/null 2>&1; then
        VERSION_FOUND=$(openclaw --version 2>/dev/null || echo "unknown")
        print_status "OpenClaw version: $VERSION_FOUND"
    fi
}

# Find config directory
find_config_dir() {
    if [ -d "$HOME/.openclaw" ]; then
        CONFIG_DIR="$HOME/.openclaw"
    elif [ -d "/etc/openclaw" ]; then
        CONFIG_DIR="/etc/openclaw"
    elif [ -d "/opt/openclaw" ]; then
        CONFIG_DIR="/opt/openclaw"
    else
        CONFIG_DIR="$HOME/.openclaw"
        mkdir -p "$CONFIG_DIR"
    fi
    
    CONFIG_FILE="$CONFIG_DIR/config.yaml"
    PLUGINS_DIR="$CONFIG_DIR/plugins"
    DATA_DIR="$CONFIG_DIR/data"
    
    print_status "Config directory: $CONFIG_DIR"
}

# Check config file
check_config() {
    print_diagnose "Checking configuration file..."
    
    if [ ! -f "$CONFIG_FILE" ]; then
        print_warning "Config file not found at $CONFIG_FILE"
        print_status "Creating default config..."
        cat > "$CONFIG_FILE" << 'EOF'
# OpenClaw Configuration
# Generated by ClawICU

server:
  host: 0.0.0.0
  port: 8080
  log-level: info

plugins:
  enabled:
    - gateway
    - monitor
    - firewall

gateway:
  upstream: 127.0.0.1:7890
  timeout: 30

monitor:
  enabled: true
  interval: 60
EOF
        print_success "Default config created"
        return 1
    fi
    
    # Validate YAML syntax
    if command -v python3 >/dev/null 2>&1; then
        if python3 -c "import yaml; yaml.safe_load(open('$CONFIG_FILE'))" 2>/dev/null; then
            print_success "Config file syntax is valid"
            return 0
        else
            print_error "Config file has syntax errors!"
            print_status "Attempting to repair..."
            backup_file "$CONFIG_FILE"
            repair_config
            return $?
        fi
    elif command -v python >/dev/null 2>&1; then
        if python -c "import yaml; yaml.safe_load(open('$CONFIG_FILE'))" 2>/dev/null; then
            print_success "Config file syntax is valid"
            return 0
        else
            print_error "Config file has syntax errors!"
            backup_file "$CONFIG_FILE"
            repair_config
            return $?
        fi
    else
        # Basic check - look for common issues
        if grep -q "^\s*:" "$CONFIG_FILE" 2>/dev/null; then
            print_warning "Config file may have syntax issues (empty keys)"
        fi
        print_success "Config file exists (basic check only)"
        return 0
    fi
}

# Backup file
backup_file() {
    BACKUP_FILE="$1.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$1" "$BACKUP_FILE"
    print_status "Backed up to: $BACKUP_FILE"
}

# Repair config file
repair_config() {
    print_status "Repairing config file..."
    
    # Create clean config
    cat > "$CONFIG_FILE" << 'EOF'
# OpenClaw Configuration
# Repaired by ClawICU

server:
  host: 0.0.0.0
  port: 8080
  log-level: info

plugins:
  enabled:
    - gateway
    - monitor

gateway:
  upstream: 127.0.0.1:7890
  timeout: 30

monitor:
  enabled: true
  interval: 60
EOF
    print_success "Config file repaired with defaults"
}

# Check OpenClaw process
check_process() {
    print_diagnose "Checking OpenClaw process..."
    
    if pgrep -f "openclaw" > /dev/null 2>&1; then
        PID=$(pgrep -f "openclaw" | head -1)
        print_success "OpenClaw is running (PID: $PID)"
        
        # Check if process is responsive
        if kill -0 "$PID" 2>/dev/null; then
            print_status "Process is responsive"
            return 0
        else
            print_error "Process $PID is not responsive"
            return 1
        fi
    else
        print_warning "OpenClaw is not running"
        return 1
    fi
}

# Check port availability
check_port() {
    local port="$1"
    print_diagnose "Checking port $port..."
    
    if command -v lsof > /dev/null 2>&1; then
        if lsof -i ":$port" > /dev/null 2>&1; then
            local proc=$(lsof -i ":$port" 2>/dev/null | grep -v PID | awk '{print $1}' | head -1)
            print_warning "Port $port is in use by: $proc"
            return 1
        fi
    elif command -v ss > /dev/null 2>&1; then
        if ss -tuln 2>/dev/null | grep -q ":$port "; then
            print_warning "Port $port is in use"
            return 1
        fi
    elif command -v netstat > /dev/null 2>&1; then
        if netstat -tuln 2>/dev/null | grep -q ":$port "; then
            print_warning "Port $port is in use"
            return 1
        fi
    fi
    
    print_success "Port $port is available"
    return 0
}

# Check plugins
check_plugins() {
    print_diagnose "Checking plugins..."
    
    if [ ! -d "$PLUGINS_DIR" ]; then
        print_warning "Plugins directory not found"
        return 1
    fi
    
    local plugin_count=$(find "$PLUGINS_DIR" -name "*.so" -o -name "*.js" 2>/dev/null | wc -l | tr -d ' ')
    print_status "Found $plugin_count plugin(s)"
    
    # Check each plugin
    for plugin in "$PLUGINS_DIR"/*.so "$PLUGINS_DIR"/*.js; do
        if [ -f "$plugin" ]; then
            local name=$(basename "$plugin")
            if ldd "$plugin" 2>/dev/null | grep -q "not found"; then
                print_error "Plugin $name has missing dependencies"
            else
                print_success "Plugin $name OK"
            fi
        fi
    done
}

# Check gateway connectivity
check_gateway() {
    print_diagnose "Checking gateway connectivity..."
    
    local upstream="127.0.0.1:7890"
    
    if command -v curl > /dev/null 2>&1; then
        if curl -sf --connect-timeout 3 "http://$upstream" > /dev/null 2>&1; then
            print_success "Gateway at $upstream is reachable"
            return 0
        else
            print_warning "Gateway at $upstream is not reachable"
            return 1
        fi
    else
        if timeout 3 nc -z "$upstream" 2>/dev/null; then
            print_success "Gateway at $upstream is reachable"
            return 0
        else
            print_warning "Gateway at $upstream is not reachable"
            return 1
        fi
    fi
}

# Full diagnosis
run_diagnosis() {
    print_header
    printf "${BOLD}${YELLOW}Running full system diagnosis...${RESET}\n\n"
    
    local issues=0
    
    if ! check_openclaw; then
        issues=$((issues + 1))
    fi
    
    find_config_dir
    
    if ! check_config; then
        issues=$((issues + 1))
    fi
    
    if ! check_process; then
        issues=$((issues + 1))
    fi
    
    check_port 8080
    
    check_plugins
    
    check_gateway
    
    printf "\n"
    if [ $issues -eq 0 ]; then
        printf "${GREEN}${BOLD}Diagnosis complete: No critical issues found${RESET}\n"
        return 0
    else
        printf "${YELLOW}${BOLD}Diagnosis complete: $issues issue(s) found${RESET}\n"
        return $issues
    fi
}

# Interactive repair menu
repair_menu() {
    print_header
    printf "${BOLD}${YELLOW}ClawICU Repair Menu${RESET}\n\n"
    printf "What would you like to do?\n\n"
    printf "  ${GREEN}1${RESET}) Run full diagnosis\n"
    printf "  ${GREEN}2${RESET}) Repair config file\n"
    printf "  ${GREEN}3${RESET}) Restart OpenClaw service\n"
    printf "  ${GREEN}4${RESET}) Fix plugin permissions\n"
    printf "  ${GREEN}5${RESET}) Kill stuck process\n"
    printf "  ${GREEN}6${RESET}) Quick fix all (config + plugins)\n"
    printf "  ${GREEN}7${RESET}) Show OpenClaw status\n"
    printf "  ${GREEN}0${RESET}) Exit\n\n"
    
    printf "Enter choice: "
}

# Quick fix all
quick_fix() {
    print_status "Running quick fix..."
    
    find_config_dir
    
    if [ -f "$CONFIG_FILE" ]; then
        backup_file "$CONFIG_FILE"
        repair_config
    fi
    
    if [ -d "$PLUGINS_DIR" ]; then
        chmod -R 755 "$PLUGINS_DIR" 2>/dev/null || true
    fi
    
    if pgrep -f "openclaw" > /dev/null 2>&1; then
        print_status "Restarting OpenClaw..."
        pkill -f "openclaw" 2>/dev/null || true
        sleep 1
    fi
    
    print_success "Quick fix complete"
    print_status "Run './rescue.sh diagnose' to verify"
}

# Install OpenClaw
install_openclaw() {
    print_status "Installing OpenClaw..."
    
    detect_os
    
    if [ "$OS" = "macos" ]; then
        if command -v brew > /dev/null 2>&1; then
            print_status "Using Homebrew..."
            brew install openclaw 2>/dev/null || {
                print_status "OpenClaw not in Homebrew, downloading binary..."
                download_binary
            }
        else
            download_binary
        fi
    else
        download_binary
    fi
}

# Download binary
download_binary() {
    print_status "Downloading OpenClaw binary..."
    
    detect_os
    
    local arch=$(uname -m)
    local download_url="https://xagent.icu/api/v1/rescue-script"
    
    if command -v curl > /dev/null 2>&1; then
        print_status "Downloading from $download_url..."
        # The actual download would go here
        # For now, just ensure we can reach the server
        if curl -sf --connect-timeout 5 "$download_url" > /dev/null 2>&1; then
            print_success "Download server is reachable"
        else
            print_error "Cannot reach download server"
        fi
    fi
}

# Main entry
main() {
    case "${1:-}" in
        diagnose|diag|d)
            run_diagnosis
            ;;
        repair|fix|r)
            quick_fix
            ;;
        status|s)
            find_config_dir
            check_openclaw
            check_process || true
            check_config || true
            ;;
        install|i)
            install_openclaw
            ;;
        *)
            # Interactive mode
            while true; do
                repair_menu
                read -r choice
                case "$choice" in
                    1) run_diagnosis ;;
                    2) find_config_dir; backup_file "$CONFIG_FILE"; repair_config ;;
                    3) 
                        if pgrep -f "openclaw" > /dev/null 2>&1; then
                            pkill -f "openclaw"
                            print_success "OpenClaw stopped"
                        fi
                        print_status "Start OpenClaw with: openclaw start"
                        ;;
                    4) 
                        if [ -d "$PLUGINS_DIR" ]; then
                            chmod -R 755 "$PLUGINS_DIR"
                            print_success "Plugin permissions fixed"
                        else
                            print_warning "Plugins dir not found"
                        fi
                        ;;
                    5) 
                        pkill -9 -f "openclaw" 2>/dev/null || true
                        print_success "Stuck processes killed"
                        ;;
                    6) quick_fix ;;
                    7) 
                        find_config_dir
                        check_openclaw
                        check_process || true
                        check_port 8080
                        ;;
                    0) 
                        printf "\n${CYAN}Thank you for using ClawICU!${RESET}\n"
                        exit 0
                        ;;
                    *)
                        print_error "Invalid choice"
                        ;;
                esac
                printf "\n"
            done
            ;;
    esac
}

main "$@"
